demo_admin_orders_mark_order:
  path: demoextendgrid/{orderId}/mark-order
  methods: [POST]
  defaults:
    _controller: PrestaShop\Module\DemoExtendGrid\Controller\DemoOrderController::markOrder
  requirements:
      orderId: \d+
